### ISSUE TITLE
Enabling nix causes LANG to be lost.

### ISSUE THREAD

**Issue by seanparsons** [commercialhaskell/stack#2358]
This took me a while to figure out, but the pre-requisites of it appear to be:
- Nix is enabled in stack.yaml.
- Code is run from within stack itself (for me it manifests with `ghcid` and by using `stack exec <binaryname>`).

An easy way to see what's going on here is this:

``` bash
# diff <(env) <(stack exec env) | grep LANG
Run from outside a project, using implicit global project config
> GDM_LANG=en_GB.utf8
> LANG=en_GB.UTF-8
< LANG=en_GB.UTF-8
< GDM_LANG=en_GB.utf8

# diff <(env) <(stack --nix exec env) | grep LANG
Run from outside a project, using implicit global project config
< LANG=en_GB.UTF-8
< GDM_LANG=en_GB.utf8
```

In my case this manifested as a failure in my code where I tried to create files with non-ASCII filenames using `Data.ByteString.writeFile`.

**Comment by seagreen** [comment]
I think this is an issue on the Nixpkgs side, see [this issue](https://github.com/NixOS/nix/issues/318) or just a [search for "lang" in their issues](https://github.com/NixOS/nix/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20lang).

**Comment by chris-martin** [comment]
It seems fair to me for a build not to inherit `LANG` from the environment. Not all projects use the same language, right?

**Comment by seagreen** [comment]
@chris-martin: Agreed. Happily it looks like nix isn't inheriting LANG:

```
[~/code/mine/hjsonschema]traveller@nivian $ export LANG=POSIX
[~/code/mine/hjsonschema]traveller@nivian $ echo $LANG
POSIX
[~/code/mine/hjsonschema]traveller@nivian $ nix-shell 

[nix-shell:~/code/mine/hjsonschema]$ echo $LANG 
en_US.UTF-8

[nix-shell:~/code/mine/hjsonschema]$
```

**Comment by seagreen** [comment]
Hmm, not I'm confused. The above uses this `stack.yml`:

```
resolver: lts-7.2
nix: 
  enable: true                                                                                              
  shell-file: shell.nix
```

Note that I haven't set `pure` to `false`. The `shell.nix` file it mentions doesn't mess with `LANG` at all.

It seems from the above that nix is no longer clearing `LANG`, but is instead defaulting it to `en_US.UTF-8`. (All of this is on nixpkgs `17.03.git.adfcc2d (Gorilla)`).

But then when I run @seanparsons' original command, `LANG` is still being unset:

```
[~/code/mine/hjsonschema]traveller@nivian $ diff <(env) <(stack --nix exec env) | grep LANG
< LANG=en_US.UTF-8
```

Anyone have an idea what's going on?

**Comment by chris-martin** [comment]
This affects a lot of things, including how `~/.ghc/ghci.conf` is read, so it will prevent you from doing things like setting a lambda as your ghci prompt.

Workaround suggestion:

**~/.stack/config.yaml**

```yaml
nix:
  enable: true
  shell-file: /home/username/.stack/shell.nix
```

**~/.stack/shell.nix**

```nix
{ pkgs ? import <nixpkgs> {}, ghc ? pkgs.ghc }:

with pkgs;

haskell.lib.buildStackProject {
  name = "default-stack-shell";
  inherit ghc;
  buildInputs = [ zlib ];
  LANG = "en_US.UTF-8";
}
```

Unfortunately I think an absolute path is the only way to specify `shell-file` here.

**Comment by fmthoma** [comment]
For me, `stack --no-nix-pure` seems to work around the issue as well. (Using stack 1.2.0 and a global config.yaml with `nix: enable: true`, no shell file).

How about some options to `stack --nix` to explicitly set environment variables even in a pure shell?

**Comment by domenkozar** [comment]
I've pushed to upstream https://github.com/NixOS/nixpkgs/commit/f4e67389ccf51c0d3a240f571724516ea9608926 that should resolve this issue

**Comment by seagreen** [comment]
@domenkozar: Just tested unstable, my problem is fixed. Thanks so much, it's really nice to have this working.

**Comment by seagreen** [comment]
@chris-martin: Oh, this is what was preventing lambda prompts! Good catch, you made me realize [this issue](https://github.com/commercialhaskell/stack/issues/2937) is fixed as well.

**Comment by mgsloan** [comment]
That's great news!

**Comment by fmthoma** [comment]
This should be fixed in NixOS 17.03, right? For me, the problem still persists:

```
> stack exec -- bash -c 'env | grep LANG'
> stack exec --no-nix-pure -c 'env | grep LANG'
LANG=en_US.UTF-8
```

Environment:

```
> nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
> sudo nix-channel --list
nixos https://nixos.org/channels/nixos-17.03
> nix-env --version
nix-env (Nix) 1.11.8nixos https://nixos.org/channels/nixos-17.03

> stack --version
Version 1.3.2 x86_64
Compiled with:
[…]
```

**Comment by Anton-Latukha** [comment]
@chris-martin 
Now you can do:
```
nix:
  enable: true
  shell-file: shell.nix
```

**Comment by WhosCounting** [comment]
Maybe I'm missing something but it looks like the issue still persists for me in 18.09.
  
```
 $ stack exec -- bash -c 'env | grep LANG'
 $ stack exec --no-nix-pure -- bash -c 'env | grep LANG'
LANG=en_US.UTF-8
LANGUAGE=
```

My environment:

```
 $ nix-channel --list
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz

 $ stack --version
Version 1.7.1 x86_64
Compiled with:

 $ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-18.09
```

**Comment by qrilka** [comment]
@WhosCounting could you explain what exactly you see as a problem? BTW verbose output from Stack should show you derivation which gets passed into a `nix-shell`. And also the latest stable version of Stack is 1.9.3 (though I doubt that it matters in this case)

**Comment by WhosCounting** [comment]
@qrilka Thanks for replying. Well, I've found this thread when I was trying to figure out why my program crashes when ran with `stack exec app-exe`. When the program would encounter a unicode char in the output it failed with a message `app-exe: <stdout>: commitBuffer: invalid argument (invalid character)`.

Testing as above for the value of `LANG` within stack environment showed that it's unset. Since executing the program directly (through `.stack-work/dist/ [...]`) and executing it with `--no-nix-pure` works, I imagine it has to do with the `LANG` variable being empty. If this is the desired behavior, sorry for the noise :)

Re stack version: I know, but this was the default in nixpkgs.

Thanks for the tip with verbosity, unfortunately the output doesn't make it clear.

**Comment by qrilka** [comment]
It's a feature of `nix-shell` (almost all env vars get cleared in pure nix), see e.g. our fix in the master - https://github.com/commercialhaskell/stack/pull/4294

**Comment by WhosCounting** [comment]
I thought the point of the fix was to enable unicode output with `--nix-pure` option. IIUC the fix ought to make the `LANG` var equal to `en_US.UTF-8`. This is not the case for me:

```
 $ stack exec --nix-pure -- bash -c locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
I also build and ran [the test](https://github.com/qrilka/stack/blob/0a30e1f733b1f94b13d208565f1f0ecd73a63939/test/integration/tests/4095-utf8-pure-nix/files/ShowUnicode.hs) included in your fix and the result was:

```
 $ stack exec --nix-pure ShowUnicode
ShowUnicode: <stdout>: commitBuffer: invalid argument (invalid character)
```

Do you have any idea what could be wrong?

**Comment by qrilka** [comment]
@WhosCounting what's the version of stack you're using here? The fix is in the `master` only, i.e. even the latest stable 1.9.3 will not give you UTF-8 but with one of the latest commits from `master` I have:
```
$ stack-head exec --nix-pure -- bash -c locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
if you need a workaround you could either use custom `shell.nix` or use impure Nix mode

**Comment by WhosCounting** [comment]
Oh, this explains everything. I'm on 1.7.1. I'll use nix impure then. Thank you very much for your patience!
