### ISSUE TITLE
Command line option `--with-gcc` is ignored

### ISSUE THREAD

**Issue by OlivierSohn** [commercialhaskell/stack#4073]
The context is that I need to use a gcc supporting the C++17 standard.

When passing `--with-gcc=c:\msys64\MINGW32\bin\gcc` to stack invocation, I was expecting that ghc would use the given gcc to build my code, but it ignores it.

### Steps to reproduce

Using a `projectWithCSources.cabal` (I use [this one](https://github.com/OlivierSohn/hamazed/blob/master/imj-audio/imj-audio.cabal)) where during c preprocessor phase, we print the compiler version like so:

```c
#define COMPILER_VERSION0(compiler,a,b,c) "compiled with " compiler " " #a "." #b "." #c
#define COMPILER_VERSION(compiler,a,b,c) COMPILER_VERSION0(compiler,a,b,c)

#ifdef __GNUC__
#  pragma message (COMPILER_VERSION("gcc",__GNUC__,__GNUC_MINOR__,__GNUC_PATCHLEVEL__))
#endif

```

Given a more recent `gcc` (located at `<path-to-new-gcc>`) than the one used when doing `stack exec -- gcc --version`

1. Run command `stack exec -- gcc --version`

This gives us `version1`

2. Run command `stack --with-gcc=<path-to-new-gcc> build`

this gives us `version2`, printed during the c-preprocessor phase

Note that this is a simplified version of [this Appveyor script](https://github.com/OlivierSohn/hamazed/blob/windows-music/appveyor.yml)

The bug happens for ghc8.2.2 (resolver `lts-11.9`) and ghc8.4.3 (resolver `nightly-2018-06-07`)

### Expected

version2 > version1

### Actual

version2 == version1

The verbose output is [available here](https://ci.appveyor.com/project/OlivierSohn/hamazed/build/1.0.91) (line 2030 is the command to build the project, line 2046 shows the gcc  version used by ghc to compile the c sources)

### Stack version

```
$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) i386 hpack-0.28.2
```

### Method of installation

```yaml
- curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-i386.zip
- 7z x stack.zip stack.exe
```

**Comment by dbaynard** [comment]
Hello, this must have fallen through the cracks. I wonder if this is related to haskell/cabal#4439. @nh2 might have some idea?

**Comment by dbaynard** [comment]
It may also relate to #3902

**Comment by OlivierSohn** [comment]
@dbaynard yes it looks like these issues are related

**Comment by nh2** [comment]
@OlivierSohn Can you try [my solution](https://www.reddit.com/r/haskell/comments/7rtg6n/how_to_compile_with_stdc11/dt1he4n/) from [this reddit thread](https://www.reddit.com/r/haskell/comments/7rtg6n/how_to_compile_with_stdc11/) which is to add to your `.cabal` file:

```
ghc-options:         -optc-std=c++14
cc-options:          -std=c++14
```

The bug mentioned in https://github.com/commercialhaskell/stack/issues/4073#issuecomment-398931882 is certainly relevant but if you are lucky it only affects a stage in cabal where it doesn't matter what the `-std` flag is, and the above might be enough.

Please report back if that helps!

**Comment by OlivierSohn** [comment]
@nh2 note that I use c++ 17, not C++ 14, and I already pass

`cc-options:          -std=c++17`

Why do you think that passing

`ghc-options:          -std=c++17` (or 14)

would make the right gcc (i.e the one I specify using the commandline option) be selected ?

**Comment by OlivierSohn** [comment]
(continued) @nh2 in your context are you using `--with-gcc` at all ? if not, I think your proposal is not relevant.

**Comment by nh2** [comment]
@OlivierSohn Ah, sorry, I misunderstood, you are right. If the compiler that's slected can't do c++17 at all, then what I said won't help.

A couple questions:

> Using a projectWithCSources.cabal (I use [this one](https://github.com/OlivierSohn/hamazed/blob/windows-music/imj-bindings-audio/imj-bindings-audio.cabal))

This link 404s for me, could you make a stable link to it?

You're giving a Windows path in `--with-gcc=c:\msys64\MINGW32\bin\gcc`; is this issue also reproducible on Linux? That might make it much easier for people to work on it.

If yes, could you provide full instructions to trigger it?

A temporary workaround might be to simply inplace-replace the GCC it's currently picking by a newer version.

**Comment by OlivierSohn** [comment]
@nh2 Ok, and I tried the suggestion, to confirm it doesn't solve the issue.

I updated the link to the .cabal (the branch was deleted in-between)

I don't know if the issue is reproducible on linux : I didn't need --with-gcc on linux (I managed to upgrade the compilers in a way that doesn't require to use --with-gcc)

What do you mean by "inplace-replace the GCC it's currently picking" exactly?

**Comment by nh2** [comment]
> What do you mean by "inplace-replace the GCC it's currently picking" exactly?

@OlivierSohn That you would replace whatever `gcc` cabal/ghc are picking now by a newer version on your file system.

**Comment by OlivierSohn** [comment]
@nh2 ok, maybe that could work, but I prefer waiting for this bug to be fixed. Thanks for the suggestion.

**Comment by Mikolaj** [comment]
Hi! Heads up about https://github.com/haskell/cabal/pull/7873, which is a PR solving this ticket that @jberryman has kindly just rebased and we are desperate to merge before it bitrots.

We need to add a small test for that or at least test the branch on the examples you have. Please help!

**Comment by Mikolaj** [comment]
Please kindly also have a look (and review) at #7900, which provides a test and discusses its result. Last chance to provide feedback before we merge. Thank you!

**Comment by OlivierSohn** [comment]
@Mikolaj Hello, I am afraid I won't have the time to test the fix. If someone has time to do it, they can follow the steps in the description to verify that the issue is fixed.

**Comment by Mikolaj** [comment]
@OlivierSohn: understood. Thank you for reporting. Should we close this issue (and re-open if anything is amiss)?

@jberryman: thank you for https://github.com/haskell/cabal/pull/7900, which is now merged, which ends the saga! Please, everybody, test the fix and report if anything is still missing. The feature should be released in cabal 3.8 (no release date planned yet).

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and the comment above about the resolution of the upstream issue.
