### ISSUE TITLE
Paths module fails prepositive-qualified-module

### ISSUE THREAD

**Issue by brandon-leapyear** [commercialhaskell/stack#5614]
### General summary/comments (optional)
Upstream issue: https://github.com/haskell/cabal/issues/7599

My understanding is that Stack hardcodes the version of Cabal it uses to generate the `Paths_*.hs` file. If this is incorrect, and Stack uses the version of Cabal in the snapshot, please close this issue. If this is correct, then Stack will need to bump the version of Cabal after Cabal releases a new version with a valid `Paths_*.hs` module.

### Steps to reproduce

1. `package.yaml` with `ghc-options: -Werror -Weverything`
2. `stack build`

### Expected

Should work

### Actual

`Paths_*.hs` module fails `-Wprepositive-qualified-module`

**Comment by phadej** [comment]
AFAIK, `stack` compiles `Setup.hs` with the version of `Cabal` in the snapshot. So until snapshots don't contain `Cabal-3.6` (which is already released), you are out of luck.

**Comment by brandon-leapyear** [comment]
Can you go into more detail there? I tried adding `extra-deps: [Cabal-3.6.0.0]`, but it still didn't work.

**Comment by phadej** [comment]
I tried to build `master` of `hpack` which uses [LTS-15.11](https://www.stackage.org/lts-15.11) In `stack build -v` output I can see lines like:

```
home/phadej/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3
```

Cabal-3.0.1.0 is one in the snapshot.

After I add `extra-deps: [Cabal-3.6.0.0]`, it's still the `_3.0.1.0` Setup. So it seems that `stack` uses the `Cabal` version bundled with GHC. That's unfortunate.

**Comment by qrilka** [comment]
@phadej is correct here, see e.g. https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml#L3083 - Cabal was shipped in some previous Stackage snapshots but some time ago it was decided that using pre-built version removes extra overhead of rebuilding Cabal and some extra maintenance burden

**Comment by brandon-leapyear** [comment]
So to summarize, we have to wait until GHC bundles a Cabal with the fix in https://github.com/haskell/cabal/pull/7352 (in either `3.4.0.1` or `3.6.0.1`, is that correct?) in which case this would only be fixed in stack snapshots with that newer GHC version?

**Comment by mrgutkun** [comment]
Regarding applicable versions of Cabal:
https://github.com/haskell/cabal/pull/7562/files should have backported the fix that lets Cabal generate nice `Paths_*` to Cabal-3.4.*, but it never did, and [as of now](https://github.com/haskell/cabal/blob/942639c18c0cd8ec53e0a6f8d120091af35312cd/Cabal/Distribution/Simple/Build/PathsModule.hs) Cabal-3.4's `Paths*` still can't be built with `-Werror -Wprepositive-qualified-module`.  
[3.6.1.0](https://github.com/haskell/cabal/releases/tag/Cabal-v3.6.1.0) does contain the backport.

Given that ghc-9.0.2 is bundled with Cabal-3.4.1.0 and ghc-9.2.1 with Cabal-3.6.0.0, it'd be nice to unbundle them somehow. Maybe with a `cabal: <version>` config not unlike the `compiler: ...` one?
